"""new fields added in user model

Revision ID: 672c1dcedefb
Revises: 79d264fc93b0
Create Date: 2019-12-23 20:34:19.195874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672c1dcedefb'
down_revision = '79d264fc93b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
