"""followers

Revision ID: 687a9dc1bc4b
Revises: 672c1dcedefb
Create Date: 2019-12-25 11:15:50.804966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687a9dc1bc4b'
down_revision = '672c1dcedefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
